sudo: required
language: bash
env:
  global:
  - LIVE_SERVICE=minionservice
  - LIVE_CLUSTER_NAME=jeevab
  - LIVE_APP_NAME=john
  - AWS_URL=037368072271.dkr.ecr.ap-south-1.amazonaws.com
services:
- docker
script:
- echo "No tests!"
after_success:
- docker-deploy/docker_push.sh
- docker-deploy/ecs_deploy.sh
